package userstore

const ERROR_EMPTY_ARRAY = "array cannot be empty"
const ERROR_EMPTY_STRING = "string cannot be empty"
const ERROR_NEGATIVE_NUMBER = "number cannot be negative"

const USER_ROLE_SUPERUSER = "superuser"
const USER_ROLE_ADMINISTRATOR = "administrator"
const USER_ROLE_MANAGER = "manager"
const USER_ROLE_USER = "user"

const USER_STATUS_ACTIVE = "active"
const USER_STATUS_INACTIVE = "inactive"
const USER_STATUS_DELETED = "deleted"
const USER_STATUS_UNVERIFIED = "unverified"

const COLUMN_BUSINESS_NAME = "business_name"
const COLUMN_CREATED_AT = "created_at"
const COLUMN_COUNTRY = "country"
const COLUMN_EMAIL = "email"
const COLUMN_FIRST_NAME = "first_name"
const COLUMN_ID = "id"
const COLUMN_MEMO = "memo"
const COLUMN_METAS = "metas"
const COLUMN_MIDDLE_NAMES = "middle_names"
const COLUMN_LAST_NAME = "last_name"
const COLUMN_PASSWORD = "password"
const COLUMN_PHONE = "phone"
const COLUMN_PROFILE_IMAGE_URL = "profile_image_url"
const COLUMN_STATUS = "status"
const COLUMN_ROLE = "role"
const COLUMN_TIMEZONE = "timezone"
const COLUMN_SOFT_DELETED_AT = "soft_deleted_at"
const COLUMN_UPDATED_AT = "updated_at"
